#+TITLE: About time

Speaking of sound, motion and video: https://www.youtube.com/watch?v=mODqQvlrgIQ

Reading the comic made me think about Brian Greene's /The Fabric of the Cosmos/ in which he uses several metaphors and visualizations to help explain the nature of this thing we call time. We tend to think we know what "now" is, and think of it as a snapshot of the current state of the world.  That model suffices in our day-to-day lives quite nicely, but it isn't a very good model of the concept of time on a universe-sized scale.  Einstein's famous Theory of relativity states that time and space are closely related, and that perception of time is relative to the observer.  The concept of "now" is also relative.  Greene uses the metaphor of a long loaf of bread, the long axis representing time, and a "slice" of the loaf representing an instant in time across a 2D universe.  The angle at which the bread is sliced depends on an observers relative motion, with a maximum angle of 45 degrees cooresponding to a maximum velocity of the speed of light.  Two observers, Bob and Alice at different relative velocities would have slices at different angles, and so their "now" slices would intersect at some line in space.  In Bob's "now" some events in Alice's "now" haven't happened yet, they're in Bob's "future", while others are in Bob's "past".
