
#+TITLE: About time

Reading the "Time Frames" comic about depicting time in comics made me
think about Brian Greene's /The Fabric of the Cosmos/ in which he uses
several [[https://www.youtube.com/watch?v%3DcbaV4O98KfE#t%3D19m50s][metaphors and visualizations]] to help explain the nature of
this thing we call time. We tend to think we know what "now" is, and
think of it as a snapshot of the current state of the world.  That
model suffices in our day-to-day lives quite nicely, but it isn't a
very good model of the concept of time on a universe-sized scale.
Einstein's famous Theory of relativity states that time and space are
closely related, and that perception of both time and space is
relative to the observer.  The concept of "now" is also relative.
Greene uses the metaphor of [[https://www.youtube.com/watch?v%3DcbaV4O98KfE#t%3D22m10s][a loaf of bread]], the long axis
representing time, and a "slice" of the loaf representing an instant
in time across a 2D universe.  The angle at which the bread is sliced
depends on an observer's relative motion, with a maximum angle of 45
degrees cooresponding to a maximum velocity of the speed of light.
Two observers, Bob and Alice at different relative velocities would
have slices at different angles, and so their "now" slices would
intersect at some line in space.  In Bob's "now" some events in
Alice's "now" haven't happened yet, they are in Bob's "future", while
others are in Bob's "past".  Time is an elusive concept, just when we
think we know what we're talking about we get hit with something like
"my 'now' isn't the same as your 'now'". It's no wonder there are so
many ways to depict its passage in the comic medium!

On a slightly related tangent, the medium used can have some
interesting affects on our perception of time and motion. In [[https://www.youtube.com/watch?v%3DmODqQvlrgIQ][this
video]], recorded at 25 frames per second, a stream of falling water
appears to freeze in time, or even flow backwards, when it interacts
with sound waves at or near 25Hz.  It's not really an optical
illusion, more of a media illusion.
