#+TITLE: As Scholars are Wont to do...
#+TAGS: brachristocrone, mutation, expression, essense

Time is an important dimension to consider when tracing the path of a
media-represented concept.  This is a theme that has stuck with me
since reading Brenda Laurel's "The Six Elements and Causal Relations
Among Them" and coming across this brilliant bit of prose:

#+BEGIN_QUOTE
As scholars are wont to do, I will blame the vagaries of translation,
figurative language, and mutations introduced by centuries of
interpretation for this apparent lapse and proceed to advocate my own
view. - Brenda Laurel, "The Six Elements and Causal Relations Among Them"
#+END_QUOTE

Which, should be noted, already inspired  [[http://blogs.lt.vt.edu/shebang/2013/03/20/we-are-the-medium-directors-cut/][a previous post]].

The particular idea that Laurel was referring to was one first
explored by Aristotle over 2000 years prior, and I was struck with an
eerie feeling that I was pulled into a conversation spanning millennia
as well as minds.  Like Michelangelo chipping away at a block of marble to
reveal the sculpture hidden within, poets and philosophers carve away
at the layers of representation in an attempt to reveal the essence of
a concept encased within.

It occurred to me that the same process is occurring in the sciences
as well, although usually the bricks of representation[fn:david] are
mathematical symbols rather than linguistic. In a moment of
serendipity, while I was musing over the conversation of this mornings
class, I opened a book on Nonlinear Geometric Control Theory that, a
few weeks back, I had checked out of the library on a whim.  If the
title means little to you, rest assure, it does me as well.  This is
not a topic I am to familiar with, but for a reason I can not fully
explain, ever since I was introduced very briefly to [[http://en.wikipedia.org/wiki/Differential_form][differential
forms]] in a [[http://en.wikipedia.org/wiki/Real_analysis][real analysis]] class I suspected that the language of
[[http://en.wikipedia.org/wiki/Differential_geometry][differential geometry]] had the potential for elegant representations of
optimal control problems.  Low and behold, I opened this book and
immediately saw a paper in which the authors, Sussmann and Willems,
explored several representations of the [[http://www-history.mcs.st-and.ac.uk/HistTopics/Brachistochrone.html][brachistochrone problem]],
concluding with a differential-geometric approach that they claimed as
the most elegant thus far.

** The brachristochrone problem

In 1696, [[http://en.wikipedia.org/wiki/Johann_Bernoulli][Johann Bernoulli]] asked a question that has become a classical
problem used as motivating example for [[http://en.wikipedia.org/wiki/Calculus_of_variations][calculus of variations]] and
rears its head again in [[http://en.wikipedia.org/wiki/Optimal_control][optimal control]][fn:lcp_approach]:

#+BEGIN_QUOTE
Given two points A and B in a vertical plane, what is the curve traced
out by a point acted on only by gravity, which starts at A and reaches
B in the shortest time. - [[http://www-history.mcs.st-and.ac.uk/HistTopics/Brachistochrone.html][The bracristochrone problem]]
#+END_QUOTE

The problem itself is older than Bernoulli: Galileo had conducted his
own exploration in 1638 and incorrectly deduce the solution to be the
arc of a circle.[fn:brachristochrone] Bernoulli's revitalization of the
question is what led to the first correct answer, that the solution is
a [[http://en.wikipedia.org/wiki/Cycloid][cycloid]].

Sussmann and Willems summarize the various solutions to the problem as follows:

#+BEGIN_QUOTE
1. Johann Bernoulli's own solution based on an analogy with geometrical optics,
2. the solution based on the classical calculus of variations,
3. the optimal control method,
and, finally,
4. the differential-geometric approach
- Sussmann & Willems
#+END_QUOTE

They demonstrate how each successive method refines the solution space
and eliminates unnecessary assumptions to approach what could be
considered the essence of the problem itself. They end with the
differential-geometric approach with the claim that it is thus far the
best at elegantly capturing the problem, but it hardly seems like this
will be the final word on such a well traveled challenge.

So it seems the path the poet takes in exploring the nature of life is
not all that dissimilar from the path the  mathematician,
scientist or engineer takes, only the tools differ, and even then,
the difference is often over stated. They are all just
different colors of bricks[fn:david].

** References
[fn:brachristochrone] [[http://www-history.mcs.st-and.ac.uk/HistTopics/Brachistochrone.html][The brachristochrone problem]]
Sussmann, Hector J. and Willems, Jan C. The brachistochrone problem and modern control theory

** Footnotes
[fn:lcp_approach] worthy of an entirely separate post: through my
digging around for more details about the [[http://www-history.mcs.st-and.ac.uk/HistTopics/Brachistochrone.html][brachistochrone problem]] I
discovered [[http://www.math.umt.edu/tmme/.../TMME_vol5nos2and3_a1_pp.169_184.pdf][a paper]] discussing it as a Large Context Problem, an
approach to education that is of extreme interest to me that I now have a name for!

[fn:david] [[https://blogs.lt.vt.edu/vtclis13/author/davidhenry/][David]], write about your brick analogy so I have something to link to!
