#+TITLE: Open Source in The Final Frontier
#+TAGS: ece2524, vtclis13, linux, open source, gpl, nasa, iss

There have been a [[https://blogs.lt.vt.edu/hussaino/2013/05/15/linux-dominating-space/][couple]] of blog posts recently referencing the recent
switch [[http://www.nasa.gov/][NASA]] made from Windows to [[http://www.debian.org/][Debian 6]], a [[http://www.gnu.org/gnu/linux-and-gnu.html][GNU/Linux]] distribution,
as the OS running on the laptops abord the [[http://www.nasa.gov/mission_pages/station/main/index.html][International Space
Station]].  It's worth noting that Linux is no stranger to the ISS, as
it has been a part of ground control operations [[http://www.linux-magazine.com/w3/issue/12/Linux_on_the_International_Space_Station.pdf%2520][since the beginning]]. 

The reasons for the space-side switch [[http://www.zdnet.com/to-the-space-station-and-beyond-with-linux-7000014958/][are quoted]] as

#+BEGIN_QUOTE
...we needed an operating system that was stable and reliable — one that would give us in-house control. So if we needed to patch, adjust, or adapt, we could.
#+END_QUOTE

This is satisfying to many Open Source/Linux fans in it's own right: a
collaborative open source project has [[http://en.wikipedia.org/wiki/Internet][once again]] proved itself more stable and
reliable for the (relatively) extrodinary conditions of low Earth
orbit than a product produced by a major software giant. Plus one for
open source collaboration and peer networks!

But theres another reason to be excited.  And it's a reason that would
not necessarily applied ([[https://www.youtube.com/watch?v%3D7XTHdcmjenI#t%3D9m08s][mostly]]) to, say, Apple fanatics had NASA
decided to switch to OS X instead of Debian. And that reason has to do
with the collaborative nature of the open source movement, codified in
many open source licenses under which the software is released.
Linux, and the GNU tools, which together make up a fully functional
operating system, are released under the [[http://www.gnu.org/copyleft/gpl.html][GNU General Public
License]]. Unlike many licenses used for commersial software, the GPL
esures that software licenses under its terms remains free for users
to use,modify and redistribute.  There are certainly some strong
criticisms and [[https://blogs.oracle.com/roumen/entry/sun_s_criticism_of_gpl][ongoing debate]] regarding some key aspects of the GPL,
especially [[http://www.osnews.com/story/19133/Torvalds_Still_Will_Not_License_Linux_Under_GPL_v3/][version 3]], the point of contention mostly lies in what is
popularly called the "viral" effect of the license: that modified and
derived work must also be released under the same license.  The GPL
might not be appropriate for every developer and every project, but it
codifies the spirit of open source software in a way that is agreeable
with many developers and users.  

So what does this all mean in terms of NASA's move?  We already know
that they chose GNU/Linux for its reliability and stability over
alternatives, but that doesn't mean it's completely bug free, or will
always work perfectly with every piece of hardware, which after all is
another reason for the switch: *no* OS will be completely bug free or
always work with all hardware, but at least Debian gives NASA the
flexibility of making improvements themselves.  And there in lies the
reason for excitement.  While there is no requirement that NASA
redistribute their own modified versions of the software, there is no
reason to assume they wouldn't in most cases, and if they do, it will
be redistributed under the same license.  It's certainly realistic to
expect they will be directly a lot of attention to making the Linux
kernel, and the GNU tools packaged with Debian even /more/ stable and
/more/ reliable, and those improvements will make their way back into
the general distributions that we all use.  This means better hardware
support for all GNU/Linux users in the future!

And of course it works both ways.  Any bug fixes /you/ make and
redistribute may make their way back to the ISS, transforming
humanity's thirst for exploring "the final frontier" into a truly
collaborative and global endeavor.


