#+TITLE: About Time: Idioms About Time
#+TAGS: time, idioms, vtclis13, ece2524s13

TL;DR: In the comments below please post, in your native language, or a non-English language in which you are fluent:
1. how you would ask someone what time it is, and the literal word-for-word translation into English
2. how you would ask someone where you are and the literal word-for-word translation into English

I wonder if I should stop being surprised when topics I've discussed separately with separate people all start to relate.  On Monday I talked about idioms in [[http://blogs.lt.vt.edu/ece2524s13][ECE2524]] and made some comparisons between idioms in programming languages to idioms in spoken languages. As I thought about examples of idioms I noticed there were quite a lot about time:

- on time 
- about time
- in time
- next time

just to name a few (I've somewhat intentionally left out more complex examples like "a watched pot never boils", "better late than never", etc.).  Today in [[http://gardnercampbell.wetpaint.com/page/vtclis13][vtclis13]] we discussed [[http://en.wikipedia.org/wiki/Scott_McCloud][McCloud's]] "Time Frames", a comic that explores the various ways time and motion are represented in comics.  Inevitably we talked about the different ways of talking about and perceiving time, from the relativistic physical properties of the dimension, to our own personal perception of the passage of time, and how in both cases the rate of time can change based on the environment.  Time is such a funny thing. We often talk about it as if we know what we're talking about and we take various metrics for granted: In the U.S. what is it about taking 16 trips around the sun that makes someone ready to drive a car? 2 more orbits and we're deemed ready to vote, and after a total of 21 orbits, after we have been on the Earth as it has traveled through about 19,740,000,000 kilometers relative to the sun, we are legally able to purchase alcohol.

But if [[http://en.wikipedia.org/wiki/Einstein][Einstein's]] [[http://en.wikipedia.org/wiki/Theory_of_relativity][forays into relativity]] have taught us anything it is that nothing about time is absolute as we generally have an intuition for. And so I became curious about the idioms we use to talk about time and how they differ from culture to culture, language to language. [[https://twitter.com/GardnerCampbell][Dr. C]] put my thought into a question: "Are idioms about time especially diverse?".  And so, through this little survey, I would like to explore that question by gathering some time idioms in the comments section, please refer back to the first paragraph for specific instructions!
